name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - 'snapshot'  # HEAD version (30.x development)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Emacs ${{ matrix.emacs-version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}
    
    - name: Install dependencies
      run: make install-deps
    
    - name: Byte compile
      run: make compile
    
    - name: Run tests
      run: make test
    
    - name: Check package loading
      run: |
        emacs -Q -batch -L . -L backends \
          --eval "(require 'poly-translate)" \
          --eval "(message \"Package loaded successfully\")"